In [2]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
df1 = pd.read_parquet('publications_full_dataset_2000-2024.parquet')
df1.head(5)

,work_id,title,display_name,abstract,doi,publication_date,publication_year,cited_by_count,ids,document type,is_oa,source_display_name,source_id,issn_l,host_organization,host_organization_name,landing_page_url,pdf_url,license,version,keywords,is_retracted,grants,primary_topic_id,primary_topic_name,primary_topic_score,primary_subfield_id,primary_subfield_name,primary_field_id,primary_field_name,primary_domain_id,primary_domain_name,funding_details,funding_text,author_keywords,index_keywords_scopus,keywords_plus_wos,authors,institutions,countries,nAuthors,institutions1,nAuthors1
0,W2128158076,Geant4—a simulation toolkit,Geant4—a simulation toolkit,GEANT4 is a toolkit for simulating the passage...,10.1016/s0168-9002(03)01368-8,2003-06-21,2003,22300.0,"[""W2128158076"",""10.1016/s0168-9002(03)01368-8""...",article,False,Nuclear Instruments and Methods in Physics Res...,S145630073,0168-9002,P4310320990,Elsevier BV,https://doi.org/10.1016/s0168-9002(03)01368-8,None,None,None,"[{""id"":""https://openalex.org/keywords/tracking...",False,None,T11044,Particle Detector Development and Performance,0.9969,subfields/3106,Nuclear and High Energy Physics,fields/31,Physics and Astronomy,domains/3,Physical Sciences,University of Fukui,Satoshi Tanaka would like to acknowledge the s...,simulation; particle interactions; geometrical...,Computer simulation; High energy physics; Nucl...,SPACE EVENT GENERATOR; ENERGY-LOSS; SCATTERING...,S. Agostinelli; M. Tropeano; John E. Allison; ...,"University of Genoa, IT; University of Manches...","CA, CH, DE, ES, FI, FR, GB, IN, IT, JP, RU, US",127.0,None,NaN
1,W2125899728,Comparison of Multiobjective Evolutionary Algo...,Comparison of Multiobjective Evolutionary Algo...,"In this paper, we provide a systematic compari...",10.1162/106365600568202,2000-06-01,2000,5352.0,"[""W2125899728"",""10.1162/106365600568202"",""2125...",article,False,Evolutionary Computation,S38677346,1063-6560,P4310315718,The MIT Press,https://doi.org/10.1162/106365600568202,None,None,None,null,False,None,T10848,Advanced Multi-Objective Optimization Algorithms,0.9999,subfields/1703,Computational Theory and Mathematics,fields/17,Computer Science,domains/3,Physical Sciences,"Alexander von Humboldt Foundation, Germany; Sw...",Kalyanmoy Deb acknowledges support from the Al...,Evolutionary algorithms; multiobjective optimi...,None,STRATEGIES,Eckart Zitzler; Lothar Thiele; Kalyanmoy Deb,"École Polytechnique Fédérale de Lausanne, CH; ...","CH, IN",3.0,None,NaN
2,W2144476887,No health without mental health,No health without mental health,About 14% of the global burden of disease has ...,10.1016/s0140-6736(07)61238-0,2007-09-01,2007,3567.0,"[""W2144476887"",""10.1016/s0140-6736(07)61238-0""...",review,False,The Lancet,S49861241,0140-6736,P4310320990,Elsevier BV,https://doi.org/10.1016/s0140-6736(07)61238-0,None,None,None,null,False,None,T10272,Mental Health Treatment and Access,0.9964,subfields/3207,Social Psychology,fields/32,Psychology,domains/2,Social Sciences,John D. and Catherine T. MacArthur Foundation;...,We thank the Lancet Global Mental Health Group...,None,acquired immune deficiency syndrome; alcohol a...,None,Martin Prince; Vikram Patel; Shekhar Saxena; M...,"King's College London, GB; London School of Hy...","CH, CN, GB, IN, IT, PK, US",7.0,None,NaN
3,W2101881391,A Randomized Trial of Letrozole in Postmenopau...,A Randomized Trial of Letrozole in Postmenopau...,"In hormone-dependent breast cancer, five years...",10.1056/nejmoa032312,2003-11-06,2003,1803.0,"[""W2101881391"",""10.1056/nejmoa032312"",""2101881...",letter,True,New England Journal of Medicine,S62468778,0028-4793,P4310320239,Massachusetts Medical Society,https://doi.org/10.1056/nejmoa032312,https://www.nejm.org/doi/pdf/10.1056/NEJMoa032...,None,publishedVersion,"[{""id"":""https://openalex.org/keywords/letrozol...",False,None,T10756,Estrogen and related hormone effects,0.9999,subfields/1311,Genetics,fields/13,"Biochemistry, Genetics and Molecular Biology",domains/1,Life Sciences,None,None,None,None,None,Paul E. Goss; James N. Ingle; Silvana Martino;...,"Princess Margaret Hospital, NZ; Mayo Clinic in...","BE, CA, CH, IN, NZ, US",18.0,None,NaN
4,W2170318505,Observation of a Narrow Charmoniumlike State i...,Observation of a Narrow Charmoniumlike State i...,We report the observation of a narrow charmoni...,10.1103/physrevlett.91.262001,2003-12-23,2003,1869.0,"[""W2170318505"",""10.1103/physrevlett.91.262001""...",article,False,Physical Review Letters,S24807848,0031-9007,P4310320261,American Physical Society,https://doi.org/10.1103/physrevlett.91.262001,None,None,None,"[{""id"":""https://openalex.org/keywords/kekb"",""d...",False,None,T10224,Quantum Chromodynamics and Particle Interactions,1.0000,subfields/3106,Nuclear and High Energy Physics,fields/31,Physics and Astronomy,domains/3,Physical Sciences,None,None,None,None,MESON; CHROMODYNAMICS; SPECTROSCOPY; ANNIHILATION,K. Abe; K. Abe; I. Adachi; K. Akai; M. Akemoto...,"High Energy Accelerator Research Organization,...","AT, AU, CH, CN, DE, FR, IN, JP, KR, PL, RU, SI...",174.0,None,NaN

In [3]:
df2 = pd.read_parquet('publication.parquet')
df2.head(5)

,work_id,title,display_name,abstract,doi,publication_date,publication_year,cited_by_count,ids,type,is_oa,source_display_name,source_id,issn_l,host_organization,host_organization_name,landing_page_url,pdf_url,license,version,topics,keywords,is_retracted,grants,author_names,author_ids,topic_names
0,https://openalex.org/W2128158076,Geant4—a simulation toolkit,Geant4—a simulation toolkit,None,https://doi.org/10.1016/s0168-9002(03)01368-8,2003-06-21,2003,22300,"[""https://openalex.org/W2128158076"",""https://d...",article,False,Nuclear Instruments and Methods in Physics Res...,https://openalex.org/S145630073,0168-9002,https://openalex.org/P4310320990,Elsevier BV,https://doi.org/10.1016/s0168-9002(03)01368-8,None,None,None,"[{""i"":1,""score"":0.9969,""id"":""https://openalex....","[{""id"":""https://openalex.org/keywords/tracking...",False,None,S. Agostinelli; John E. Allison; B. R. Ko; J. ...,A5019950553; A5102846098; A5009376065; A505619...,Engineering; Medicine; Nuclear reactor physics...
1,https://openalex.org/W2125899728,Comparison of Multiobjective Evolutionary Algo...,Comparison of Multiobjective Evolutionary Algo...,"In this paper, we provide a systematic compari...",https://doi.org/10.1162/106365600568202,2000-06-01,2000,5352,"[""https://openalex.org/W2125899728"",""https://d...",article,False,Evolutionary Computation,https://openalex.org/S38677346,1063-6560,https://openalex.org/P4310315718,The MIT Press,https://doi.org/10.1162/106365600568202,None,None,None,"[{""i"":1,""score"":0.9999,""id"":""https://openalex....",null,False,None,Eckart Zitzler; Kalyanmoy Deb; Lothar Thiele,A5031698269; A5088394271; A5060999697,Metaheuristic Optimization Algorithms Research...
2,https://openalex.org/W2144476887,No health without mental health,No health without mental health,None,https://doi.org/10.1016/s0140-6736(07)61238-0,2007-09-01,2007,3567,"[""https://openalex.org/W2144476887"",""https://d...",review,False,The Lancet,https://openalex.org/S49861241,0140-6736,https://openalex.org/P4310320990,Elsevier BV,https://doi.org/10.1016/s0140-6736(07)61238-0,None,None,None,"[{""i"":1,""score"":0.9964,""id"":""https://openalex....",null,False,None,Martin Prince; Vikram Patel; Shekhar Saxena; M...,A5051774516; A5070156674; A5025675403; A510542...,General Health Professions; Child and Adolesce...
3,https://openalex.org/W2101881391,A Randomized Trial of Letrozole in Postmenopau...,A Randomized Trial of Letrozole in Postmenopau...,"In hormone-dependent breast cancer, five years...",https://doi.org/10.1056/nejmoa032312,2003-11-06,2003,1803,"[""https://openalex.org/W2101881391"",""https://d...",letter,True,New England Journal of Medicine,https://openalex.org/S62468778,0028-4793,https://openalex.org/P4310320239,Massachusetts Medical Society,https://doi.org/10.1056/nejmoa032312,https://www.nejm.org/doi/pdf/10.1056/NEJMoa032...,None,publishedVersion,"[{""i"":1,""score"":0.9999,""id"":""https://openalex....","[{""id"":""https://openalex.org/keywords/letrozol...",False,None,Paul E. Goss; James N. Ingle; Silvana Martino;...,A5109239396; A5083904553; A5112774196; A507548...,Medicine; Genetics; Breast Cancer Treatment St...
4,https://openalex.org/W2170318505,Observation of a Narrow Charmoniumlike State i...,Observation of a Narrow Charmoniumlike State i...,We report the observation of a narrow charmoni...,https://doi.org/10.1103/physrevlett.91.262001,2003-12-23,2003,1783,"[""https://openalex.org/W2170318505"",""https://d...",article,False,Physical Review Letters,https://openalex.org/S24807848,0031-9007,https://openalex.org/P4310320261,American Physical Society,https://doi.org/10.1103/physrevlett.91.262001,None,None,None,"[{""i"":1,""score"":1,""id"":""https://openalex.org/T...","[{""id"":""https://openalex.org/keywords/kekb"",""d...",False,None,S.-K. Choi; S. L. Olsen; K. Abe; I. Adachi; By...,A5049278896; A5051581351; A5055484840; A510786...,Particle physics theoretical and experimental ...

In [3]:
df3 = pd.read_parquet('institutional_relationships_IN_CH.parquet')
df3.head(5)

,institution_name,country_code,work_ids,n_publications,n_authors,author_names
0,ETH Zurich,CH,W1140317928; W129941269; W137420606; W14593491...,3448,3274,A-M Lyon; A Datta; A Nardulli; A.-M. Lyon; A. ...
1,University of Zurich,CH,W1237811388; W137420606; W1459349108; W1481233...,2834,2257,A Cimental Chavez; A Haeffner; A T M Tanveer H...
2,European Organization for Nuclear Research,CH,W129941269; W137420606; W1459349108; W14812335...,2802,8693,A Aurora; A Belyaev; A Bjorkebo; A Bocci; A Da...
3,École Polytechnique Fédérale de Lausanne,CH,W104589452; W109130197; W1140245919; W11674819...,2105,1787,A. Amraoui; A. Babu; A. Bay; A. Biland; A. Cam...
4,Paul Scherrer Institute,CH,W137420606; W1484847134; W1500527695; W1507197...,1876,832,A. Amato; A. Barczyk; A. Benaglia; A. Bergamas...

In [9]:
for i in df3['institution_name'].values:
    print(i)

ETH Zurich
University of Zurich
European Organization for Nuclear Research
École Polytechnique Fédérale de Lausanne
Paul Scherrer Institute
World Health Organization
University of Geneva
University of Bern
Novartis (Switzerland)
University of Basel
University of Lausanne
University Hospital of Bern
University Hospital of Zurich
University Hospital of Basel
Swiss Tropical and Public Health Institute
University Hospital of Geneva
Roche (Switzerland)
University of Fribourg
Swiss Federal Laboratories for Materials Science and Technology
University of Neuchâtel
Board of the Swiss Federal Institutes of Technology
University Hospital of Lausanne
SIB Swiss Institute of Bioinformatics
Foundation for Innovative New Diagnostics
Swiss Federal Institute for Forest, Snow and Landscape Research
Union for International Cancer Control
University Children's Hospital Zurich
Swiss Federal Institute of Aquatic Science and Technology
University of Applied Sciences and Arts of Southern Switzerland
Drugs for Neglected Diseases Initiative
HES-SO University of Applied Sciences and Arts Western Switzerland
International Union for Conservation of Nature
University of St. Gallen
Medicines for Malaria Venture
International Labour Organization
STMicroelectronics (Switzerland)
Idiap Research Institute
Graduate Institute of International and Development Studies
FHNW University of Applied Sciences and Arts
Università della Svizzera italiana
Agroscope
The Geneva Association
Biocon (Switzerland)
Accenture (Switzerland)
World Heart Federation
Institute of Social and Preventive Medicine
Luzerner Kantonsspital
International Council of Nurses
ABB (Switzerland)
Global Fund to Fight AIDS, Tuberculosis and Malaria
Oeschger Centre for Climate Change Research
Breast Center
Dalle Molle Institute for Artificial Intelligence Research
Bristol-Myers Squibb (Switzerland)
University of Lucerne
World Meteorological Organization
Janssen (Switzerland)
University of St.Gallen
Syngenta (Switzerland)
Alliance for Health Policy and Systems Research
Joint United Nations Programme on HIV/AIDS
Global Alliance for Improved Nutrition
Hôpital Beau-Séjour
ZHAW Zurich University of Applied Sciences
Synopsys (Switzerland)
World Trade Organization
Swiss Institute of Comparative Law
Istituto Ricerche Solari Locarno
Kantonsspital St. Gallen
CK-CARE
Nestlé (Switzerland)
Forschungsinstitut für Biologischen Landbau
IBM Research - Zurich
University Children’s Hospital Basel
Service de la Santé Publique
Swiss School of Public Health
Mylan (Switzerland)
Institute of Molecular and Clinical Ophthalmology Basel
Ascom (Switzerland)
Médecins Sans Frontières
Institute of Oncology Research
Rhizen Pharmaceuticals (Switzerland)
Toyota Motor Corporation (Switzerland)
AO Foundation
Friedrich Miescher Institute
Kantonsspital Aarau
Gavi
Clayton Foundation
Institute for Biomedical Engineering
Klinik Sonnenhof
Frontier Science Foundation
Addiction Switzerland
Global Forum for Health Research
Actelion (Switzerland)
Biogen (Switzerland)
Merck Serono (Switzerland)
Global Antibiotic Research & Development Partnership
International Space Science Institute
Physikalisch-Meteorologisches Observatorium Davos
Ente Ospedaliero Cantonale
Federal Office of Meteorology and Climatology MeteoSwiss
Adolphe Merkle Institute
AstraZeneca (Switzerland)
Clinique de Genolier
Novo Nordisk (Switzerland)
Victoria School of Management
Centre universitaire de médecine générale et santé publique, Lausanne
Bioengineering (Switzerland)
European Society for Medical Oncology
Swiss Integrative Center for Human Health
United Nations Economic Commission for Europe
International Institute for Management Development
Natural History Museum of Geneva
Novartis Foundation
Bern University of Applied Sciences
Kantonsspital Winterthur
CSL (Switzerland)
Kantonsschule Olten
Lucerne University of Applied Sciences and Arts
Developing Countries Vaccine Manufactures Network
European Society of Clinical Microbiology and Infectious Diseases
EU Business School
Hôpital Riviera-Chablais
Pfizer (Switzerland)
Spital Thurgau (Switzerland)
Hirslanden Klinik Beau-Site
Kantonsspital Baselland
HES-SO Genève
International Organization for Migration
Triemli Hospital
Dr. Reddy's Laboratories (Switzerland)
AOSpine
Malik Management (Switzerland)
Fondation Asile des Aveugles
Federal Office for Agriculture
Swiss Ornithological Institute
World Economic Forum
Bioanalytica (Switzerland)
Charles Humbert 8
Ospedale regionale di Lugano
Office of the United Nations High Commissioner for Refugees
Institute for Medical Informatics and Biostatistics
World Wide Fund for Nature
Universitätsklinik Balgrist
Swiss Paraplegic Research
Care International
Takeda (Switzerland)
International Breast Cancer Study Group
Concept Foundation
Conservatory and Botanical Garden of the City of Geneva
Octapharma (Switzerland)
Terre des Hommes
Glenmark Pharmaceuticals (Switzerland)
Swiss Group For Clinical Cancer Research
Swiss Center for Electronics and Microtechnology (Switzerland)
Alexion Pharma (Switzerland)
Google (Switzerland)
Natural History Museum of Bern
International Committee of the Red Cross
International Museum of Horology
European Respiratory Society
Centre d'Imagerie BioMedicale
Credit Suisse (Switzerland)
International Olympic Committee
World Federation of Public Health Associations
Hôpital Ophtalmique Jules-Gonin
Institut de Recherche en Opthalmologie
GlaxoSmithKline (Switzerland)
Orchid (Switzerland)
Klinik Hirslanden
Human Computer Interaction (Switzerland)
Swisscom (Switzerland)
Hamilton Medical (Switzerland)
European Stroke Organisation
Inspire
HES-SO Valais-Wallis
Hexagon (Switzerland)
Hirslanden Klinik St. Anna
Bayer (Switzerland)
Ferring Pharmaceuticals (Switzerland)
Varian Medical Systems (Switzerland)
Swiss Federal Institute of Metrology
Foundation for Research on Information Technologies in Society
Kantonsspital Graubünden
Center for Pediatric Endocrinology Zurich
Switch
Swiss Finance Institute
Felix Platter-Hospital
Fribourg Development Agency
Union Bank of Switzerland
Vifor Pharma (Switzerland)
Foundation for laboratory medicine
Sarmap (Switzerland)
Bank for International Settlements
Zimmer Biomet (Switzerland)
University Children’s Hospital Bern
Past Global Changes
Intergovernmental Panel on Climate Change
Swiss Red Cross
Vestergaard (Switzerland)
Hirslanden Klinik Im Park
Hôpital de Sion
Epatocentro Ticino
MSD (Switzerland)
Sight and Life
Unitaid
Universitäre Psychiatrische Kliniken Basel
Swiss Academy of Sciences
Swiss National Science Foundation
Alstom (Switzerland)
International Social Security Association
Ospedale San Giovanni Bellinzona
Schulthess-Klinik
Tofwerk (Switzerland)
Ludwig Cancer Research
Philip Morris International (Switzerland)
Centre de Recherche sur l'Environnement Alpin
Département de la Santé et de l'Action Sociale
Générale-Beaulieu Clinic
SIS Medical (Switzerland)
Edwards Lifesciences (Switzerland)
CABI Switzerland
St. Claraspital
Siemens (Switzerland)
School of Engineering and Architecture of Fribourg
Ospedale Regionale di Bellinzona e Valli
Spiez Laboratory
Amt für Umwelt
Haute École Pédagogique du Canton de Vaud
Swiss Re (Switzerland)
Amgen (Switzerland)
Hôpital Orthopédique de la Suisse Romande
Molecular Partners (Switzerland)
Swiss Paraplegic Center
Gamma Remote Sensing (Switzerland)
Medicines Patent Pool
Biologie Labor
Alcon (Switzerland)
International Federation of Sports Medicine
Business School Lausanne
European League Against Rheumatism
FDI World Dental Federation
Ziemer Ophthalmic Systems (Switzerland)
Sigma-Tau (Switzerland)
Berner Augenklinik am Lindenhofspital
Bruker (Switzerland)
Ostschweizer Kinderspital
Foederatio Medicorum Helveticorum
Schneeberger (Switzerland)
Stiftung Patientensicherheit Schweiz
Spital Linth
Hirslanden Clinique Bois-Cerf
Systems, Applications & Products in Data Processing (Switzerland)
Martel
Pädagogische Hochschule Bern
Hôpital de la Tour
Federal Roads Office
Smith & Nephew (Switzerland)
Medtronic (Switzerland)
Enter (Switzerland)
Swiss Cancer League
Wyss Center for Bio and Neuroengineering
Luc Hoffmann Institute
Universitäres Zentrum für Zahnmedizin Basel
Mintaka Foundation for Medical Research
Institut Icare
Laboratory for Biomedical Neurosciences
Solaronix (Switzerland)
Galderma (Switzerland)
Ostschweizer Fachhochschule OST
ELZA Institute
Universitätsklinik für Augenheilkunde
International Federation of Red Cross and Red Crescent Societies
Klinik für Schlafmedizin
Kantonsspital Baselland Standort Bruderholz
Sulzer (Switzerland)
Colgate-Palmolive (Switzerland)
Kantonsspital Baden
Lonza (Switzerland)
Service de Santé de la Jeunesse
Mettler-Toledo (Switzerland)
Ordecsys (Switzerland)
DSM (Switzerland)
Musée d'Art et d'Histoire
Observatoire Cantonal de Neuchâtel
Hirslanden Klinik Stephanshorn
Debiopharm (Switzerland)
European School of Oncology
Natural History Museum of Basel
International Centre for Trade and Sustainable Development
Hirslanden Klinik Aarau
Musée cantonal de zoologie de Lausanne
Georg Fischer (Switzerland)
Sophia Genetics (Switzerland)
See-Spital
Zurich Heart House
Elekta (Switzerland)
NCCR Chemical Biology - Visualisation and Control of Biological Processes Using Chemistry
Multidisciplinary Digital Publishing Institute (Switzerland)
Intuitive Surgical (Switzerland)
Organizzazione Sociopsichiatrica Cantonale
Fondation Botnar
Hightec MC (Switzerland)
Reha Rheinfelden
GastroZentrum Hirslanden Zürich
University Centre of Legal Medicine
Swiss Cancer Center Léman
Applied Pharma Research (Switzerland)
Procter & Gamble (Switzerland)
Gesundheitsdienst
Zentrum für Labormedizin
Helsana Group (Switzerland)
Psychiatry Baselland
Zürich Airport (Switzerland)
Battelle
Hirslanden Clinique La Colline
AGRIDEA
Cell Medica (Switzerland)
Saab (Switzerland)
Boehringer Ingelheim (Switzerland)
Helsinn (Switzerland)
Hirslanden Clinique Cecil
BASF (Switzerland)
Stadtspital Waid
SCQM Foundation
Clinica Luganese Moncucco
Solothurner Spitäler
Biotronik (Switzerland)
Büchi Labortechnik
Federal Food Safety and Veterinary Office
Scuola Cantonale di Commercio Bellinzona
Verein für Krebsforschung
Cereneo
Schwyz University of Teacher Education
Straumann (Switzerland)
Schweizerische Ärztegesellschaft für Psycholytische Therapie
International AIDS Society
Weatherford (Switzerland)
Clinique de La Source
World Intellectual Property Organization
Hirslanden Clinique des Grangettes
Swiss National Park
Vir Biotechnology (Switzerland)
Aga Khan Development Network
Swiss Epilepsy Center
Hirslanden Private Hospital Group
University of Teacher Education Lucerne
Syngenta Foundation for Sustainable Agriculture
Hospital Neuchâtel
Clinique Romande de Réadaptation
Academia Engiadina
Business and Hotel Management School
Council on Health Research for Development
Kantonsspital Frauenfeld
Hôpital du Valais
Zurich University of Applied Sciences in Business Administration
Adecco (Switzerland)
International Telecommunication Union
ADR-AC (Switzerland)
Hôpital régional
TE Connectivity (Switzerland)
Scherrer (Switzerland)
Webster University Geneva
Spital Lachen
Universitäre Psychiatrische Dienste Bern
Delley Seeds and Plants (Switzerland)
Swiss Federal Office of Energy
Swiss Vaccine Research Institute
In Silico Toxicology (Switzerland)
Spital Uster
Forel Klinik
Johnson & Johnson (Switzerland)
Japan Tobacco (Switzerland)
Link Institut (Switzerland)
Federal Office of Public Health
Polyclinic Medical University
Clariant (Switzerland)
Office Médico Pédagogique
Med Discovery (Switzerland)
RMS Foundation
Hôpital de Morges
Basilea Pharmaceutica (Switzerland)
Ospedale Regionale di Locarno
Global Social Observatory
Leman University
Tumor- und Brustzentrum ZeTuP Silberturm
Firmenich (Switzerland)
Karger Publishers (Switzerland)
L.A.C. (Switzerland)
Allergan (Switzerland)
Light Chain Bioscience (Switzerland)
CFS Engineering (Switzerland)
Service Régional Vaudois de Transfusion Sanguine
Zimmer (Switzerland)
Schindler (Switzerland)
Ithaka Institute for Carbon Strategies
Sunrise Communications AG (Switzerland)
Saurer (Switzerland)
Hochgebirgsklinik Davos
Centre Alpien de Phytogéographie
Universitätsklinik für Diabetologie, Endokrinologie, Ernährungsmedizin & Metabolismus
Kalaidos University of Applied Sciences
Federal Supreme Court of Switzerland
Federal Office for the Environment
University of Teacher Education Zug
HES-SO Fribourg
GZO Spital Wetzikon
Swiss Health Observatory
European Society of Gynaecological Oncology
Hôpital de la Providence
Stiftung für Forschung in Spätantike und Mittelalter HR. Sennhauser
Kantonsarchäologie Aargau
FORS – Swiss Centre of Expertise in the Social Sciences
Lindenhofspital
Institute for Independent Studies Zürich
EuroSpine
Swiss HIV Cohort Study
Hôpital intercantonal de la Broye
Hôpital du Jura Bernois
Zug Cantonal Hospital
Spitäler Schaffhausen
Women's Brain Project
University of Applied Sciences Rapperswil
Swissmedic
Bethesda Spital
Biognosys (Switzerland)
Swiss Data Science Center
Treeze (Switzerland)
General Electric (Switzerland)
HES-SO Arc
Genkyotex (Switzerland)
Alpine Biology Center
Swiss Institute for Regenerative Medicine
Schwery Consulting (Switzerland)
Abbott (Switzerland)
Givaudan (Switzerland)
Istituto Cantonale di Patologia
SIGVARIS Group (Switzerland)
Klinik Bethesda
3Brain (Switzerland)
Virtuelle Fabrik (Switzerland)
Institution de Lavigny
Zürcher Fachhochschule
Albrecht von Haller Foundation
United Nations Institute for Disarmament Research
Kone (Switzerland)
Freiwillige Akademische Gesellschaft
Institute for Work and Health
Gene Signal (Switzerland)
Hydrosolutions (Switzerland)
Neurotune (Switzerland)
Edelweiss Connect (Switzerland)
Exalos (Switzerland)
Evolva (Switzerland)
Anton Paar (Switzerland)
Aga Khan Foundation
Interstate University of Applied Sciences of Technology Buchs
Ammann (Switzerland)
Amt für Hochbauten
Ecoplan (Switzerland)
143-Gnosca
Gulf Research Center
Herzgefäss Medizin Klinik Im Park
Hôpital Nestlé
Hocoma (Switzerland)
Federal Statistical Office
Rosenthaler + Partner (Switzerland)
Children's Oncology Group
Fluxim (Switzerland)
BG Consulting Engineers (Switzerland)
Hexis (Switzerland)
Delenex (Switzerland)
SwissScientific Technologies (Switzerland)
Cardinal Health (Switzerland)
Sonnenhalde (Switzerland)
Flisom (Switzerland)
Santhera Pharmaceuticals (Switzerland)
Horphag Research (Switzerland)
Koenig & Bauer (Switzerland)
Hôpital de Beaumont
Oekoscience (Switzerland)
Swiss National Bank
Zurich Insurance Group (Switzerland)
Swiss Federal Nuclear Safety Inspectorate
C&A Foundation (Switzerland)
Weleda (Switzerland)
IBSA Institut Biochimique (Switzerland)
Swiss Institute of Equine Medicine
Acorda Therapeutics (Switzerland)
Microsoft (Switzerland)
Springer Nature (Switzerland)
Institute for Work Research and Organizational Consultancy
Genedata (Switzerland)
University of Teacher Education in Special Needs
National Cooperative for the Disposal of Radioactive Waste (Switzerland)
Suss Microoptics (Switzerland)
Metabo (Switzerland)
Tecan (Switzerland)
Wockhardt (Switzerland)
St.Gallen University of Teacher Education
Seecon (Switzerland)
Honeywell (Switzerland)
Interface Politikstudien (Switzerland)
Memoriav
Endress+Hauser (Switzerland)
Siegfried (Switzerland)
Fairmed
Tamedia (Switzerland)
Quantis (Switzerland)
Labormedizinische Zentrum Dr Risch (Switzerland)
Franklin University Switzerland
Meteotest (Switzerland)
Gymnase de Nyon
Zürich Zoological Garden
Centre for Medically Assisted Procreation
Integrierte Psychiatrie Winterthur
Zurich University of Teacher Education
UniDistance Suisse
Dialog Ethik
GeoModelling Solutions (Switzerland)
European Academy of Allergy and Clinical Immunology
Liceo Cantonale
Kantonsschule Zug
VersuchsStollen Hagerbach (Switzerland)
Immunologie-Zentrum Zürich
Kunstmuseum Basel
Edmond J. Safra Philanthropic Foundation
Omya (Switzerland)
Spital Zollikerberg
Winterthur Gas & Diesel (Switzerland)
Life Science Zurich
AC Immune (Switzerland)
Technik und Forschung im Betonbau (Switzerland)
Cemex (Switzerland)
Prognos (Switzerland)
Réseau Fribourgeois de Santé Mentale
SHL Medical (Switzerland)
Sonova (Switzerland)
International Alliance for Biological Standardization
Nursing Science Foundation Switzerland
Robert Kennedy College
James Lind Institute
Possover International Medical Center
Terra Quantum (Switzerland)
Brocher Foundation
International Baccalaureate
Collegium Helveticum
Center for Business Studies
Swiss Federal Railways
Stiftung Lindenhof Bern
Sintetica (Switzerland)
United Nations Educational, Scientific and Cultural Organization Switzerland
Hirslanden Salem-Spital
Swiss Distance University of Applied Sciences
Swiss Federal Institute of Sport Magglingen SFISM
Med-Consilium (Switzerland)
Stryker (Switzerland)
Engeriedspital
THIM van der Laan University College Physiotherapy
Schaffner (Switzerland)
Sanatorium Kilchberg
United Nations Institute for Training and Research
AZAD Pharma (Switzerland)
PregLem (Switzerland)
Thomson Reuters (Switzerland)
Museum of Fine Arts Bern
Synthena (Switzerland)
Hôpital de l'enfance
Max Zeller Söhne (Switzerland)
Teva Pharmaceuticals (Switzerland)
HiQScreen (Switzerland)
Tillotts Pharma (Switzerland)
Walt Disney (Switzerland)
Sensirion (Switzerland)
Federal Department of Economic Affairs, Education and Research
University of Applied Sciences St. Gallen
Swiss Federal University for Vocational Education and Training SFUVET
Klinik Barmelweid
Tata Institute of Fundamental Research
Panjab University
Saha Institute of Nuclear Physics
University of Delhi
Bhabha Atomic Research Centre
Indian Institute of Technology Madras
National Institute of Science Education and Research
Indian Institute of Science Bangalore
Indian Institute of Science Education and Research Pune
Indian Institute of Technology Bombay
Novartis (India)
Variable Energy Cyclotron Centre
Homi Bhabha National Institute
Aligarh Muslim University
All India Institute of Medical Sciences
Indian Institute of Technology Indore
Indian Institute of Technology Hyderabad
University of Jammu
Institute of Physics, Bhubaneshwar
Bose Institute
Indian Institute of Technology Guwahati
University of Rajasthan
Cancer Institute (WIA)
Indian Institute of Technology Kanpur
Post Graduate Institute of Medical Education and Research
Indian Institute of Technology Delhi
Gauhati University
Inter-University Centre for Astronomy and Astrophysics
Christian Medical College, Vellore
World Health Organization Regional Office for South-East Asia
Tata Memorial Hospital
Manipal Academy of Higher Education
Public Health Foundation of India
Banaras Hindu University
Indian Institute of Technology Kharagpur
Indian Institute of Science Education and Research Kolkata
Indian Council of Medical Research
GlaxoSmithKline (India)
Indian Institute of Technology Bhubaneswar
Savitribai Phule Pune University
Indian Institute of Science Education and Research Mohali
Jawaharlal Nehru University
Institute of Medical Sciences
Physical Research Laboratory
Government of India
Christ University
Indian Institute of Technology Gandhinagar
Institute for Plasma Research
National Institute of Mental Health and Neurosciences
World Health Organization - India
National Centre for Biological Sciences
International Centre for Theoretical Sciences
Bharathidasan University
University of Hyderabad
Indian Institute of Technology Roorkee
King George's Medical University
Confederation of Indian Industry
Boehringer Ingelheim (India)
Sanjay Gandhi Post Graduate Institute of Medical Sciences
Raja Ramanna Centre for Advanced Technology
Government Medical College
United Nations Children's Fund India
George Institute for Global Health
Chennai Mathematical Institute
Jadavpur University
Punjab Agricultural University
Visva-Bharati University
Utkal University
Indian Statistical Institute
Kasturba Medical College, Manipal
Ministry of Health and Family Welfare
Indian Institute of Astrophysics
Society for Applied Studies
Harish-Chandra Research Institute
Solid State Physics Laboratory
Indian Institute of Science Education and Research, Bhopal

In [1]:
import pandas as pd

In [4]:
df = pd.read_parquet('authors_summary_in_ch.parquet')
df.head()

,author_id,name,orcid,nWorks,total_institutions,total_countries,n_corresponding_works,institution_work_counts,country_work_counts,collab_status
0,A5016202220,C. Tully,0000-0001-6771-2174,1716,38,21,1,"[{'institutions': 'Princeton University, US', ...","[{'countries': 'US', 'n_works': 1421}, {'count...",Both
1,A5019356592,J. B. Singh,0000-0001-9029-2462,1704,38,17,0,"[{'institutions': 'Panjab University, IN', 'n_...","[{'countries': 'IN', 'n_works': 1468}, {'count...",Joint
2,A5062459935,K. F. Chen,0000-0003-1304-3782,1699,29,13,0,"[{'institutions': 'National Taiwan University,...","[{'countries': 'TW', 'n_works': 1387}, {'count...",CH
3,A5107247482,S. Choi,0000-0001-6225-9876,1674,40,16,0,"[{'institutions': 'Korea University, KR', 'n_w...","[{'countries': 'KR', 'n_works': 1357}, {'count...",Both
4,A5072449178,V. Bhatnagar,0000-0002-8392-9610,1660,26,15,0,"[{'institutions': 'Panjab University, IN', 'n_...","[{'countries': 'IN', 'n_works': 1425}, {'count...",Joint

In [5]:
df.shape

(89302, 10)

In [6]:
df['collab_status'].value_counts()

collab_status
CH       53290
IN       28404
Joint     5886
Both      1722
Name: count, dtype: int64